version: '3'

services:
  web:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./confnginx/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    restart: always

volumes:
  html:
  nginx.conf:
